package cn.xyz.chaos.examples.demo.repository.mapper;

import cn.xyz.chaos.examples.demo.entity.Appraise;
import cn.xyz.chaos.examples.demo.entity.criteria.AppraiseCriteria;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import cn.xyz.chaos.orm.mybatis.MyBatisRepository;

@MyBatisRepository
public interface AppraiseMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table appraise
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int countByCriteria(AppraiseCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table appraise
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int deleteByCriteria(AppraiseCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table appraise
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int deleteByPrimaryKey(Integer appraiseId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table appraise
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int insert(Appraise record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table appraise
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int insertSelective(Appraise record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table appraise
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    List<Appraise> selectByCriteriaWithRowbounds(AppraiseCriteria criteria, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table appraise
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    List<Appraise> selectByCriteria(AppraiseCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table appraise
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    Appraise selectByPrimaryKey(Integer appraiseId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table appraise
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByCriteriaSelective(@Param("record") Appraise record, @Param("example") AppraiseCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table appraise
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByCriteria(@Param("record") Appraise record, @Param("example") AppraiseCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table appraise
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByPrimaryKeySelective(Appraise record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table appraise
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByPrimaryKey(Appraise record);
}
