package cn.xyz.chaos.examples.demo.repository.mapper;

import cn.xyz.chaos.examples.demo.entity.Favorite;
import cn.xyz.chaos.examples.demo.entity.criteria.FavoriteCriteria;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import cn.xyz.chaos.orm.mybatis.MyBatisRepository;

@MyBatisRepository
public interface FavoriteMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table favorite
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int countByCriteria(FavoriteCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table favorite
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int deleteByCriteria(FavoriteCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table favorite
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int deleteByPrimaryKey(Integer favoriteId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table favorite
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int insert(Favorite record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table favorite
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int insertSelective(Favorite record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table favorite
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    List<Favorite> selectByCriteriaWithRowbounds(FavoriteCriteria criteria, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table favorite
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    List<Favorite> selectByCriteria(FavoriteCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table favorite
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    Favorite selectByPrimaryKey(Integer favoriteId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table favorite
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByCriteriaSelective(@Param("record") Favorite record, @Param("example") FavoriteCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table favorite
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByCriteria(@Param("record") Favorite record, @Param("example") FavoriteCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table favorite
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByPrimaryKeySelective(Favorite record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table favorite
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByPrimaryKey(Favorite record);
}
