package cn.xyz.chaos.examples.demo.repository.mapper;

import cn.xyz.chaos.examples.demo.entity.ProdSkuOption;
import cn.xyz.chaos.examples.demo.entity.criteria.ProdSkuOptionCriteria;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import cn.xyz.chaos.orm.mybatis.MyBatisRepository;

@MyBatisRepository
public interface ProdSkuOptionMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_option
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int countByCriteria(ProdSkuOptionCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_option
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int deleteByCriteria(ProdSkuOptionCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_option
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int deleteByPrimaryKey(Integer skuOptionId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_option
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int insert(ProdSkuOption record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_option
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int insertSelective(ProdSkuOption record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_option
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    List<ProdSkuOption> selectByCriteriaWithRowbounds(ProdSkuOptionCriteria criteria, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_option
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    List<ProdSkuOption> selectByCriteria(ProdSkuOptionCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_option
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    ProdSkuOption selectByPrimaryKey(Integer skuOptionId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_option
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByCriteriaSelective(@Param("record") ProdSkuOption record,
            @Param("example") ProdSkuOptionCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_option
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByCriteria(@Param("record") ProdSkuOption record, @Param("example") ProdSkuOptionCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_option
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByPrimaryKeySelective(ProdSkuOption record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_option
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByPrimaryKey(ProdSkuOption record);
}
