package cn.xyz.chaos.examples.demo.repository.mapper;

import cn.xyz.chaos.examples.demo.entity.ProdInfo;
import cn.xyz.chaos.examples.demo.entity.criteria.ProdInfoCriteria;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import cn.xyz.chaos.orm.mybatis.MyBatisRepository;

@MyBatisRepository
public interface ProdInfoMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int countByCriteria(ProdInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int deleteByCriteria(ProdInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int deleteByPrimaryKey(Integer prodId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int insert(ProdInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int insertSelective(ProdInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    List<ProdInfo> selectByCriteriaWithBLOBsWithRowbounds(ProdInfoCriteria criteria, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    List<ProdInfo> selectByCriteriaWithBLOBs(ProdInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    List<ProdInfo> selectByCriteriaWithRowbounds(ProdInfoCriteria criteria, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    List<ProdInfo> selectByCriteria(ProdInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    ProdInfo selectByPrimaryKey(Integer prodId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByCriteriaSelective(@Param("record") ProdInfo record, @Param("example") ProdInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByCriteriaWithBLOBs(@Param("record") ProdInfo record, @Param("example") ProdInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByCriteria(@Param("record") ProdInfo record, @Param("example") ProdInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByPrimaryKeySelective(ProdInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(ProdInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByPrimaryKey(ProdInfo record);
}
