package cn.xyz.chaos.examples.demo.repository.mapper;

import cn.xyz.chaos.examples.demo.entity.ProdSkuLink;
import cn.xyz.chaos.examples.demo.entity.criteria.ProdSkuLinkCriteria;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import cn.xyz.chaos.orm.mybatis.MyBatisRepository;

@MyBatisRepository
public interface ProdSkuLinkMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_link
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    int countByCriteria(ProdSkuLinkCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_link
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    int deleteByCriteria(ProdSkuLinkCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_link
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    int deleteByPrimaryKey(Integer skuLinkId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_link
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    int insert(ProdSkuLink record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_link
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    int insertSelective(ProdSkuLink record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_link
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    List<ProdSkuLink> selectByCriteriaWithRowbounds(ProdSkuLinkCriteria criteria, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_link
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    List<ProdSkuLink> selectByCriteria(ProdSkuLinkCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_link
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    ProdSkuLink selectByPrimaryKey(Integer skuLinkId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_link
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    int updateByCriteriaSelective(@Param("record") ProdSkuLink record, @Param("example") ProdSkuLinkCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_link
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    int updateByCriteria(@Param("record") ProdSkuLink record, @Param("example") ProdSkuLinkCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_link
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    int updateByPrimaryKeySelective(ProdSkuLink record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku_link
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    int updateByPrimaryKey(ProdSkuLink record);
}
