package cn.xyz.chaos.examples.demo.repository.mapper;

import cn.xyz.chaos.examples.demo.entity.ProdSku;
import cn.xyz.chaos.examples.demo.entity.criteria.ProdSkuCriteria;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import cn.xyz.chaos.orm.mybatis.MyBatisRepository;

@MyBatisRepository
public interface ProdSkuMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int countByCriteria(ProdSkuCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int deleteByCriteria(ProdSkuCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int deleteByPrimaryKey(Integer skuId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int insert(ProdSku record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int insertSelective(ProdSku record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    List<ProdSku> selectByCriteriaWithRowbounds(ProdSkuCriteria criteria, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    List<ProdSku> selectByCriteria(ProdSkuCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    ProdSku selectByPrimaryKey(Integer skuId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByCriteriaSelective(@Param("record") ProdSku record, @Param("example") ProdSkuCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByCriteria(@Param("record") ProdSku record, @Param("example") ProdSkuCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByPrimaryKeySelective(ProdSku record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table prod_sku
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByPrimaryKey(ProdSku record);
}
