package cn.xyz.chaos.examples.demo.repository.mapper;

import cn.xyz.chaos.examples.demo.entity.UserInfo;
import cn.xyz.chaos.examples.demo.entity.criteria.UserInfoCriteria;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import cn.xyz.chaos.orm.mybatis.MyBatisRepository;

@MyBatisRepository
public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int countByCriteria(UserInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int deleteByCriteria(UserInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    List<UserInfo> selectByCriteriaWithRowbounds(UserInfoCriteria criteria, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    List<UserInfo> selectByCriteria(UserInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    UserInfo selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByCriteriaSelective(@Param("record") UserInfo record, @Param("example") UserInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByCriteria(@Param("record") UserInfo record, @Param("example") UserInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    int updateByPrimaryKey(UserInfo record);
}
