package cn.xyz.chaos.examples.demo.web.dvo;

import java.util.Date;

public class ProdInfoDTO {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column prod_info.prod_id
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    private Integer prodId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column prod_info.com_id
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column prod_info.prod_name
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    private String prodName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column prod_info.prod_alias
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    private String prodAlias;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * prod_info.limit_quantity
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    private Integer limitQuantity;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column prod_info.weight
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    private Boolean weight;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column prod_info.status
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column prod_info.adder_id
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    private Integer adderId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column prod_info.updater_id
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    private Integer updaterId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column prod_info.add_time
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * prod_info.update_time
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column prod_info.prod_pic
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    private byte[] prodPic;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_info.prod_id
     *
     * @return the value of prod_info.prod_id
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public Integer getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_info.prod_id
     *
     * @param prodId the value for prod_info.prod_id
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public void setProdId(Integer prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_info.com_id
     *
     * @return the value of prod_info.com_id
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_info.com_id
     *
     * @param comId the value for prod_info.com_id
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_info.prod_name
     *
     * @return the value of prod_info.prod_name
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_info.prod_name
     *
     * @param prodName the value for prod_info.prod_name
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public void setProdName(String prodName) {
        this.prodName = prodName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_info.prod_alias
     *
     * @return the value of prod_info.prod_alias
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public String getProdAlias() {
        return prodAlias;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_info.prod_alias
     *
     * @param prodAlias the value for prod_info.prod_alias
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public void setProdAlias(String prodAlias) {
        this.prodAlias = prodAlias;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_info.limit_quantity
     *
     * @return the value of prod_info.limit_quantity
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public Integer getLimitQuantity() {
        return limitQuantity;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_info.limit_quantity
     *
     * @param limitQuantity the value for prod_info.limit_quantity
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public void setLimitQuantity(Integer limitQuantity) {
        this.limitQuantity = limitQuantity;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_info.weight
     *
     * @return the value of prod_info.weight
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public Boolean getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_info.weight
     *
     * @param weight the value for prod_info.weight
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public void setWeight(Boolean weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_info.status
     *
     * @return the value of prod_info.status
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_info.status
     *
     * @param status the value for prod_info.status
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_info.adder_id
     *
     * @return the value of prod_info.adder_id
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public Integer getAdderId() {
        return adderId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_info.adder_id
     *
     * @param adderId the value for prod_info.adder_id
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public void setAdderId(Integer adderId) {
        this.adderId = adderId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_info.updater_id
     *
     * @return the value of prod_info.updater_id
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public Integer getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_info.updater_id
     *
     * @param updaterId the value for prod_info.updater_id
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public void setUpdaterId(Integer updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_info.add_time
     *
     * @return the value of prod_info.add_time
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_info.add_time
     *
     * @param addTime the value for prod_info.add_time
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_info.update_time
     *
     * @return the value of prod_info.update_time
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_info.update_time
     *
     * @param updateTime the value for prod_info.update_time
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_info.prod_pic
     *
     * @return the value of prod_info.prod_pic
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public byte[] getProdPic() {
        return prodPic;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_info.prod_pic
     *
     * @param prodPic the value for prod_info.prod_pic
     *
     * @mbggenerated Mon Aug 11 16:02:42 CST 2014
     */
    public void setProdPic(byte[] prodPic) {
        this.prodPic = prodPic;
    }
}
