package cn.xyz.chaos.examples.showcase.entity;

import java.util.Date;

public class Permission {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ACC_PERMISSIOIN.ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ACC_PERMISSIOIN.NAME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ACC_PERMISSIOIN.KEYWORD
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ACC_PERMISSIOIN.DESCRIPTION
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ACC_PERMISSIOIN.CREATE_TIME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ACC_PERMISSIOIN.CREATE_USER_ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ACC_PERMISSIOIN.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ACC_PERMISSIOIN.UPDATE_USER_ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private Long updateUserId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_PERMISSIOIN.ID
     *
     * @return the value of ACC_PERMISSIOIN.ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ACC_PERMISSIOIN.ID
     *
     * @param id the value for ACC_PERMISSIOIN.ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_PERMISSIOIN.NAME
     *
     * @return the value of ACC_PERMISSIOIN.NAME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ACC_PERMISSIOIN.NAME
     *
     * @param name the value for ACC_PERMISSIOIN.NAME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_PERMISSIOIN.KEYWORD
     *
     * @return the value of ACC_PERMISSIOIN.KEYWORD
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ACC_PERMISSIOIN.KEYWORD
     *
     * @param keyword the value for ACC_PERMISSIOIN.KEYWORD
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_PERMISSIOIN.DESCRIPTION
     *
     * @return the value of ACC_PERMISSIOIN.DESCRIPTION
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ACC_PERMISSIOIN.DESCRIPTION
     *
     * @param description the value for ACC_PERMISSIOIN.DESCRIPTION
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_PERMISSIOIN.CREATE_TIME
     *
     * @return the value of ACC_PERMISSIOIN.CREATE_TIME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ACC_PERMISSIOIN.CREATE_TIME
     *
     * @param createTime the value for ACC_PERMISSIOIN.CREATE_TIME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_PERMISSIOIN.CREATE_USER_ID
     *
     * @return the value of ACC_PERMISSIOIN.CREATE_USER_ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ACC_PERMISSIOIN.CREATE_USER_ID
     *
     * @param createUserId the value for ACC_PERMISSIOIN.CREATE_USER_ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_PERMISSIOIN.UPDATE_TIME
     *
     * @return the value of ACC_PERMISSIOIN.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ACC_PERMISSIOIN.UPDATE_TIME
     *
     * @param updateTime the value for ACC_PERMISSIOIN.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_PERMISSIOIN.UPDATE_USER_ID
     *
     * @return the value of ACC_PERMISSIOIN.UPDATE_USER_ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ACC_PERMISSIOIN.UPDATE_USER_ID
     *
     * @param updateUserId the value for ACC_PERMISSIOIN.UPDATE_USER_ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }
}
