package cn.xyz.chaos.examples.showcase.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ACC_USER.ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ACC_USER.NAME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ACC_USER.NICK_NAME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ACC_USER.EMAIL
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ACC_USER.MOBILE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ACC_USER.STATUS
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ACC_USER.WEIBO_URL
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private String weiboUrl;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ACC_USER.DOUBAN_URL
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private String doubanUrl;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ACC_USER.SIGNATURE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ACC_USER.CREATE_TIME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ACC_USER.CREATE_USER_ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ACC_USER.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ACC_USER.UPDATE_USER_ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private Long updateUserId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ACC_USER.ID
     *
     * @return the value of ACC_USER.ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ACC_USER.ID
     *
     * @param id the value for ACC_USER.ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_USER.NAME
     *
     * @return the value of ACC_USER.NAME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ACC_USER.NAME
     *
     * @param name the value for ACC_USER.NAME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_USER.NICK_NAME
     *
     * @return the value of ACC_USER.NICK_NAME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ACC_USER.NICK_NAME
     *
     * @param nickName the value for ACC_USER.NICK_NAME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_USER.EMAIL
     *
     * @return the value of ACC_USER.EMAIL
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ACC_USER.EMAIL
     *
     * @param email the value for ACC_USER.EMAIL
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_USER.MOBILE
     *
     * @return the value of ACC_USER.MOBILE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ACC_USER.MOBILE
     *
     * @param mobile the value for ACC_USER.MOBILE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_USER.STATUS
     *
     * @return the value of ACC_USER.STATUS
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ACC_USER.STATUS
     *
     * @param status the value for ACC_USER.STATUS
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_USER.WEIBO_URL
     *
     * @return the value of ACC_USER.WEIBO_URL
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public String getWeiboUrl() {
        return weiboUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ACC_USER.WEIBO_URL
     *
     * @param weiboUrl the value for ACC_USER.WEIBO_URL
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setWeiboUrl(String weiboUrl) {
        this.weiboUrl = weiboUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_USER.DOUBAN_URL
     *
     * @return the value of ACC_USER.DOUBAN_URL
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public String getDoubanUrl() {
        return doubanUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ACC_USER.DOUBAN_URL
     *
     * @param doubanUrl the value for ACC_USER.DOUBAN_URL
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setDoubanUrl(String doubanUrl) {
        this.doubanUrl = doubanUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_USER.SIGNATURE
     *
     * @return the value of ACC_USER.SIGNATURE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ACC_USER.SIGNATURE
     *
     * @param signature the value for ACC_USER.SIGNATURE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_USER.CREATE_TIME
     *
     * @return the value of ACC_USER.CREATE_TIME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ACC_USER.CREATE_TIME
     *
     * @param createTime the value for ACC_USER.CREATE_TIME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_USER.CREATE_USER_ID
     *
     * @return the value of ACC_USER.CREATE_USER_ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ACC_USER.CREATE_USER_ID
     *
     * @param createUserId the value for ACC_USER.CREATE_USER_ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_USER.UPDATE_TIME
     *
     * @return the value of ACC_USER.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ACC_USER.UPDATE_TIME
     *
     * @param updateTime the value for ACC_USER.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ACC_USER.UPDATE_USER_ID
     *
     * @return the value of ACC_USER.UPDATE_USER_ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ACC_USER.UPDATE_USER_ID
     *
     * @param updateUserId the value for ACC_USER.UPDATE_USER_ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }
}
