#set($symbol_pound='#')#set($symbol_dollar='$')#set($symbol_escape='\')package ${package}.repository.mapper;

import ${package}.entity.Account;import ${package}.entity.criteria.AccountCriteria;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import cn.xyz.chaos.orm.mybatis.MyBatisRepository;

@MyBatisRepository
public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.ACC_ACCOUNT
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int countByCriteria(AccountCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.ACC_ACCOUNT
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int deleteByCriteria(AccountCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.ACC_ACCOUNT
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.ACC_ACCOUNT
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.ACC_ACCOUNT
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.ACC_ACCOUNT
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    List<Account> selectByCriteriaWithRowbounds(AccountCriteria criteria, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.ACC_ACCOUNT
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    List<Account> selectByCriteria(AccountCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.ACC_ACCOUNT
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    Account selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.ACC_ACCOUNT
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int updateByCriteriaSelective(@Param("record") Account record, @Param("example") AccountCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.ACC_ACCOUNT
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int updateByCriteria(@Param("record") Account record, @Param("example") AccountCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.ACC_ACCOUNT
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.ACC_ACCOUNT
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int updateByPrimaryKey(Account record);
}
