package cn.xyz.chaos.examples.showcase.repository.mapper;

import cn.xyz.chaos.examples.showcase.entity.Permission;
import cn.xyz.chaos.examples.showcase.entity.criteria.PermissionCriteria;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import cn.xyz.chaos.orm.mybatis.MyBatisRepository;

@MyBatisRepository
public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_PERMISSIOIN
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int countByCriteria(PermissionCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_PERMISSIOIN
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int deleteByCriteria(PermissionCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_PERMISSIOIN
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_PERMISSIOIN
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_PERMISSIOIN
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_PERMISSIOIN
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    List<Permission> selectByCriteriaWithRowbounds(PermissionCriteria criteria, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_PERMISSIOIN
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    List<Permission> selectByCriteria(PermissionCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_PERMISSIOIN
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    Permission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_PERMISSIOIN
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int updateByCriteriaSelective(@Param("record") Permission record, @Param("example") PermissionCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_PERMISSIOIN
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int updateByCriteria(@Param("record") Permission record, @Param("example") PermissionCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_PERMISSIOIN
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_PERMISSIOIN
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int updateByPrimaryKey(Permission record);
}
