package cn.xyz.chaos.examples.showcase.repository.mapper;

import cn.xyz.chaos.examples.showcase.entity.Role;
import cn.xyz.chaos.examples.showcase.entity.criteria.RoleCriteria;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import cn.xyz.chaos.orm.mybatis.MyBatisRepository;

@MyBatisRepository
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_ROLE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int countByCriteria(RoleCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_ROLE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int deleteByCriteria(RoleCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_ROLE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_ROLE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_ROLE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_ROLE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    List<Role> selectByCriteriaWithRowbounds(RoleCriteria criteria, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_ROLE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    List<Role> selectByCriteria(RoleCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_ROLE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_ROLE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int updateByCriteriaSelective(@Param("record") Role record, @Param("example") RoleCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_ROLE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int updateByCriteria(@Param("record") Role record, @Param("example") RoleCriteria criteria);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_ROLE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ACC_ROLE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    int updateByPrimaryKey(Role record);
}
