package cn.xyz.chaos.examples.quickstart.entity;

public class Account {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * PUBLIC.ACC_ACCOUNT.ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * PUBLIC.ACC_ACCOUNT.PASSWORD
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * PUBLIC.ACC_ACCOUNT.NAME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * PUBLIC.ACC_ACCOUNT.NICK_NAME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * PUBLIC.ACC_ACCOUNT.EMAIL
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * PUBLIC.ACC_ACCOUNT.MOBILE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * PUBLIC.ACC_ACCOUNT.STATUS
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * PUBLIC.ACC_ACCOUNT.ID
     *
     * @return the value of PUBLIC.ACC_ACCOUNT.ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * PUBLIC.ACC_ACCOUNT.ID
     *
     * @param id the value for PUBLIC.ACC_ACCOUNT.ID
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * PUBLIC.ACC_ACCOUNT.PASSWORD
     *
     * @return the value of PUBLIC.ACC_ACCOUNT.PASSWORD
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * PUBLIC.ACC_ACCOUNT.PASSWORD
     *
     * @param password the value for PUBLIC.ACC_ACCOUNT.PASSWORD
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * PUBLIC.ACC_ACCOUNT.NAME
     *
     * @return the value of PUBLIC.ACC_ACCOUNT.NAME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * PUBLIC.ACC_ACCOUNT.NAME
     *
     * @param name the value for PUBLIC.ACC_ACCOUNT.NAME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * PUBLIC.ACC_ACCOUNT.NICK_NAME
     *
     * @return the value of PUBLIC.ACC_ACCOUNT.NICK_NAME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * PUBLIC.ACC_ACCOUNT.NICK_NAME
     *
     * @param nickName the value for PUBLIC.ACC_ACCOUNT.NICK_NAME
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * PUBLIC.ACC_ACCOUNT.EMAIL
     *
     * @return the value of PUBLIC.ACC_ACCOUNT.EMAIL
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * PUBLIC.ACC_ACCOUNT.EMAIL
     *
     * @param email the value for PUBLIC.ACC_ACCOUNT.EMAIL
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * PUBLIC.ACC_ACCOUNT.MOBILE
     *
     * @return the value of PUBLIC.ACC_ACCOUNT.MOBILE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * PUBLIC.ACC_ACCOUNT.MOBILE
     *
     * @param mobile the value for PUBLIC.ACC_ACCOUNT.MOBILE
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * PUBLIC.ACC_ACCOUNT.STATUS
     *
     * @return the value of PUBLIC.ACC_ACCOUNT.STATUS
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * PUBLIC.ACC_ACCOUNT.STATUS
     *
     * @param status the value for PUBLIC.ACC_ACCOUNT.STATUS
     *
     * @mbggenerated Mon Jul 28 13:47:12 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}
