package cn.xyz.chaos.examples.demo.entity;

import java.util.Date;

import cn.xyz.chaos.orm.annotations.Table;

@Table(name = "appraise", schema = "chaos_demo")
public class Appraise {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column appraise.appraise_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Integer appraiseId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column appraise.user_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column appraise.prod_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Integer prodId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column appraise.content
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column appraise.score
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column appraise.add_time
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appraise.appraise_id
     *
     * @return the value of appraise.appraise_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Integer getAppraiseId() {
        return appraiseId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appraise.appraise_id
     *
     * @param appraiseId the value for appraise.appraise_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setAppraiseId(Integer appraiseId) {
        this.appraiseId = appraiseId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appraise.user_id
     *
     * @return the value of appraise.user_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appraise.user_id
     *
     * @param userId the value for appraise.user_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appraise.prod_id
     *
     * @return the value of appraise.prod_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Integer getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appraise.prod_id
     *
     * @param prodId the value for appraise.prod_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setProdId(Integer prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appraise.content
     *
     * @return the value of appraise.content
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appraise.content
     *
     * @param content the value for appraise.content
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appraise.score
     *
     * @return the value of appraise.score
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column appraise.score
     *
     * @param score the value for appraise.score
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appraise.add_time
     *
     * @return the value of appraise.add_time
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appraise.add_time
     *
     * @param addTime the value for appraise.add_time
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}
