package cn.xyz.chaos.examples.demo.entity;

import java.util.Date;

public class CompanyInfo {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column company_info.com_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * company_info.com_name
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private String comName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column company_info.status
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * company_info.add_time
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * company_info.com_id
     *
     * @return the value of company_info.com_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * company_info.com_id
     *
     * @param comId the value for company_info.com_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * company_info.com_name
     *
     * @return the value of company_info.com_name
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public String getComName() {
        return comName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * company_info.com_name
     *
     * @param comName the value for company_info.com_name
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setComName(String comName) {
        this.comName = comName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * company_info.status
     *
     * @return the value of company_info.status
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * company_info.status
     *
     * @param status the value for company_info.status
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * company_info.add_time
     *
     * @return the value of company_info.add_time
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * company_info.add_time
     *
     * @param addTime the value for company_info.add_time
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}
