package cn.xyz.chaos.examples.demo.entity;

import java.util.Date;

public class Favorite {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column favorite.favorite_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Integer favoriteId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column favorite.user_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column favorite.prod_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Integer prodId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column favorite.add_time
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * favorite.favorite_id
     *
     * @return the value of favorite.favorite_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Integer getFavoriteId() {
        return favoriteId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * favorite.favorite_id
     *
     * @param favoriteId the value for favorite.favorite_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setFavoriteId(Integer favoriteId) {
        this.favoriteId = favoriteId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * favorite.user_id
     *
     * @return the value of favorite.user_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * favorite.user_id
     *
     * @param userId the value for favorite.user_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * favorite.prod_id
     *
     * @return the value of favorite.prod_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Integer getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * favorite.prod_id
     *
     * @param prodId the value for favorite.prod_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setProdId(Integer prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * favorite.add_time
     *
     * @return the value of favorite.add_time
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * favorite.add_time
     *
     * @param addTime the value for favorite.add_time
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}
