package cn.xyz.chaos.examples.demo.entity;

public class ProdSkuOption {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * prod_sku_option.sku_option_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Integer skuOptionId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * prod_sku_option.sku_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Integer skuId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * prod_sku_option.option_name
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private String optionName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * prod_sku_option.weight
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Integer weight;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_sku_option.sku_option_id
     *
     * @return the value of prod_sku_option.sku_option_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Integer getSkuOptionId() {
        return skuOptionId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_sku_option.sku_option_id
     *
     * @param skuOptionId the value for prod_sku_option.sku_option_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setSkuOptionId(Integer skuOptionId) {
        this.skuOptionId = skuOptionId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_sku_option.sku_id
     *
     * @return the value of prod_sku_option.sku_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_sku_option.sku_id
     *
     * @param skuId the value for prod_sku_option.sku_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_sku_option.option_name
     *
     * @return the value of prod_sku_option.option_name
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public String getOptionName() {
        return optionName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_sku_option.option_name
     *
     * @param optionName the value for prod_sku_option.option_name
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setOptionName(String optionName) {
        this.optionName = optionName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_sku_option.weight
     *
     * @return the value of prod_sku_option.weight
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_sku_option.weight
     *
     * @param weight the value for prod_sku_option.weight
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }
}
