package cn.xyz.chaos.examples.demo.entity;

public class ProdSkuLink {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * prod_sku_link.sku_link_id
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    private Integer skuLinkId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * prod_sku_link.prod_id
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    private Integer prodId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * prod_sku_link.sku_option_id
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    private Integer skuOptionId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_sku_link.sku_link_id
     *
     * @return the value of prod_sku_link.sku_link_id
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    public Integer getSkuLinkId() {
        return skuLinkId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_sku_link.sku_link_id
     *
     * @param skuLinkId the value for prod_sku_link.sku_link_id
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    public void setSkuLinkId(Integer skuLinkId) {
        this.skuLinkId = skuLinkId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_sku_link.prod_id
     *
     * @return the value of prod_sku_link.prod_id
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    public Integer getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_sku_link.prod_id
     *
     * @param prodId the value for prod_sku_link.prod_id
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    public void setProdId(Integer prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_sku_link.sku_option_id
     *
     * @return the value of prod_sku_link.sku_option_id
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    public Integer getSkuOptionId() {
        return skuOptionId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_sku_link.sku_option_id
     *
     * @param skuOptionId the value for prod_sku_link.sku_option_id
     *
     * @mbggenerated Thu Aug 28 10:51:25 CST 2014
     */
    public void setSkuOptionId(Integer skuOptionId) {
        this.skuOptionId = skuOptionId;
    }
}
