package cn.xyz.chaos.examples.demo.entity;

public class ProdSku {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column prod_sku.sku_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Integer skuId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column prod_sku.sku_name
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private String skuName;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_sku.sku_id
     *
     * @return the value of prod_sku.sku_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column prod_sku.sku_id
     *
     * @param skuId the value for prod_sku.sku_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * prod_sku.sku_name
     *
     * @return the value of prod_sku.sku_name
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * prod_sku.sku_name
     *
     * @param skuName the value for prod_sku.sku_name
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName;
    }
}
