package cn.xyz.chaos.examples.demo.entity;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.email
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.password
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.type
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.status
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.add_time
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * user_info.update_time
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * user_info.email
     *
     * @return the value of user_info.email
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.email
     *
     * @param email the value for user_info.email
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * user_info.password
     *
     * @return the value of user_info.password
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * user_info.password
     *
     * @param password the value for user_info.password
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * user_info.type
     *
     * @return the value of user_info.type
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.type
     *
     * @param type the value for user_info.type
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * user_info.status
     *
     * @return the value of user_info.status
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * user_info.status
     *
     * @param status the value for user_info.status
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * user_info.add_time
     *
     * @return the value of user_info.add_time
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * user_info.add_time
     *
     * @param addTime the value for user_info.add_time
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * user_info.update_time
     *
     * @return the value of user_info.update_time
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * user_info.update_time
     *
     * @param updateTime the value for user_info.update_time
     *
     * @mbggenerated Mon Aug 25 10:22:14 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
